### ISSUE TITLE
Inline table-value functions not included

### ISSUE THREAD

**Issue by FabriceGazin** [justinlettau/sql-source-control#11]
Hi, thanks for this very useful module: but in my case it works properly for the Multi-Statement Table-Valued functions, but not the inline table-valued functions. Am I missing something?

**Comment by FabriceGazin** [comment]
Found the issue: you have to include 'IF' object types, not only 'TF' and 'FN' :)

**Comment by justinlettau** [comment]
Thanks for identifying the source of the issue! I'll try to get this fixed and released soon.

**Comment by FabriceGazin** [comment]
Perfect, it works as expected! Thanks a lot!
