### ISSUE TITLE
ssc pull does not create code for CLUSTERED index

### ISSUE THREAD

**Issue by cesarcoatl** [justinlettau/sql-source-control#130]
## Describe the Issue
I have a table where the composite PK is `NONCLUSTERED` and an additional `CLUSTERED` index.

Running `ssc pull [conn]` only creates `NONCLUSTERED` indexes.

## Expected behavior
Running `ssc pull [conn]` should create the DDL for the `CLUSTERED` and `NONCLUSTERED` index.

## Steps to Reproduce
Sample table:
```sql
CREATE TABLE [dbo].[module]
(
    [project_code] [nvarchar](50),
    [display_name] [nvarchar](50),
    [position] [tinyint] NOT NULL,
    ...,
    CONSTRAINT [PK_dbo_module] PRIMARY KEY NONCLUSTERED
    (
        [project_code],
        [display_name]
    )
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_dbo_module] ******/
CREATE CLUSTERED INDEX [IX_dbo_module] ON [dbo].[module]
(
    [project_code] ASC,
    [position] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```

1. Create table
1. Run `ssc pull`
1. DDL on `dbo.module.sql` reads the following for the index

The following DDL is created:
```sql
--- CREATE TABLE DDL
--- FK DDL
IF NOT EXISTS (SELECT 1 FROM sys.indexes WJERE objexct_od = OBJECT_ID('[dbo].[module]') AND name = 'IX_dbo_module')
CREATE NONCLUSTERED INDEX [IX_dbo_module] ON [dbo].[module](
    [project_code] ASC,
    [position] ASC
)
```

## Other Information
I have forked this repo and added the necessary changes for creating CLUSTERED indexes here:
thecesrom/sql-source-control@38f5a41e9c353574aab52bc11c76417c3faf4716

I'll be more than happy to create a PR and contribute to this great project.

Thanks!

**Comment by justinlettau** [comment]
@thecesrom A PR would be great! Thanks!

**Comment by cesarcoatl** [comment]
I have found some areas for improvement:

1. Create separate `DROP` scripts for `TRIGGER`s, `PROCEDURE`s, and `FOREIGN KEY`s when using `if-exists-drop`, just as when you choose to `Generate Scripts` for a database in Microsoft SQL Server Management Studio, the order in which objects are dropped is important
1. Including an `idemPotency` option for `schemas`; when using `if-exists-drop` will override all settings for other objects because you can't drop the schema without dropping all dependent objects
1. Create `UNIQUE` constraints using the T-SQL style, where it is declared as a `CONSTRAINT` instead of an `INDEX`
1. `CHECK` constraints
1. Computed columns may be `PERSISTED` and nullable
1. Column order in an `INDEX` is important; added sorting on `key_sorting` from `sys.index_columns`

All of these (and maybe more) can be found here: thecesrom/sql-source-control@9ee8c204436cd8e64d2762789c44021e104d7792

This is my first go at TypeScript and npm packages, so please pardon any mistake I might have made.

I am aware that my changes are somewhat destructive, hence I added them to a different branch.

If you'd like to chat, you can send an email or find me on Twitter.
