### ISSUE TITLE
SSC stalls after `pull`

### ISSUE THREAD

**Issue by winzig** [justinlettau/sql-source-control#139]
I'm running SSC 2.1.1 with Node 12.6.0, connecting to SQL Server running at AWS RDS. 

When I run `ssc pull`, I get the "Successfully ..." line telling me what changed, but then ssc never seems to quit. I always have to hit CTRL-C to close it. (This doesn't seem to have any ill effect on the results, but can't really tell for sure.)

**Comment by justinlettau** [comment]
@winzig Can you try with v3.0.0 and see if it's still an issue?

**Comment by winzig** [comment]
@justinlettau Fixed! thank you!
