### ISSUE TITLE
Permissions Required

### ISSUE THREAD

**Issue by r3draid3r04** [justinlettau/sql-source-control#167]
## Type

What kind of issue is this?

```
[x ] Bug report.
[ ] Feature request.
```

## Description the Issue

What permissions are needed for this to work? I know it works with sa but I don't what this to run with sa. Thanks!

Todo

## Steps to Reproduce

n/a

## Other Information

n/a

**Comment by justinlettau** [comment]
You should only need permissions to run the queries found [here](https://github.com/justinlettau/sql-source-control/blob/master/src/queries/mssql.ts). Read access to the system tables is probably the minimum permissions needed.
