### ISSUE TITLE
Any way to encrypt the database connection info? Or separate it?

### ISSUE THREAD

**Issue by winzig** [justinlettau/sql-source-control#28]
## Type
What kind of issue is this?

```
[ ] Bug report.
[x] Feature request.
```

## Current Behavior

My SQL connection properties are in plaintext in the ssc.json file.
In the same file is other configuration data. There doesn't appear to be a way to encrypt the database properties, nor use more than one configuration file.

## Expected behavior

It would be desirable to be able to encrypt the database connection properties on disk. And/or some way to define the other (less sensitive) configuration details elsewhere. The goal being that we can check in as much as possible to GitHub, without checking in sensitive database connection data.

**Comment by justinlettau** [comment]
@winzig I like this. Do you currently store your connection info in something like a `ConnectionStrings.config` file or elsewhere?

Here is some options that could be implemented (easier than encryption):
1. Optionally, store credentials in separate config file (`ssc-credentials.json`).
2. Add support for reading connection info from `Web.config` files that use the `configSource` attribute.
3. Make `password` property on connections optional, and prompt user in CLI for password each time.

Thoughts?

**Comment by winzig** [comment]
Currently we store the connection info for other applications in the environment variables, encrypted. But that is sort of bespoke so probably not ideal for this project. I think the most secure option would be to store the password credentials in a separate file, that the app creates during the first use. Then it could encrypt the password (if one is used), before writing it.

**Comment by justinlettau** [comment]
Ok, i'll start by adding support for credentials in a separate file. Will circle back to the encryption later. 

I think it makes more sense to move the whole connections array to a separate file. In theory, this would allow each user of a repo to save their own personal connections and not check them in. The `ssc-connections.json` file could be added to the gitignore, and the shared config (`ssc.json`) can be checked-in. It would look something like this:

```js
// ssc.json
{
  // array of connection objects
  "connections": [{
    "name": "dev",
    ...
  }],

  // ... OR, path to Web.config file with connectionStrings
  "connections": "../Web.config",

  // ... OR, path to ssc-connections.json file
  "connections": "./ssc-connections.json",
}
```

If you see any issues with that, let me now. Thanks!

**Comment by winzig** [comment]
This looks great, thanks.

**Comment by justinlettau** [comment]
@winzig This will be available when v1.9.0 is released.

**Comment by justinlettau** [comment]
@winzig Just published v1.9.0. Let me know if you have any issues with it!

**Comment by winzig** [comment]
@justinlettau The connection stuff is working great, thanks. However, was something done to change the ordering of the generated SQL in the .sql files? Previously things seemed to be alphabetical, but I ran `ssc pull` just now, and it looks like all of my files have changed, but just in the ordering of the generated SQL. ¯\\__💩__/¯

**Comment by justinlettau** [comment]
@winzig Yes, the table scripting has been changed to retain the original order of the columns instead of alphabetizing them. See #33 for reference.

**Comment by winzig** [comment]
OK cool, I like that change, just wanted to make sure it was expected. Thanks!
