### ISSUE TITLE
Only obtaining a directory of tables and nothing more

### ISSUE THREAD

**Issue by ryanhinton** [justinlettau/sql-source-control#4]
Hello,

I'm attempting to use this for the first time and I ran `ssc pull` and it is only created a "tables" directory with all of the tables and nothing else such as stored procedures, functions, etc.  Am I possibly missing something?  I originally used `ssc init` to create the config which looks correct and did connect.  I then added "output" and "idempotency" details in the config exactly like your example and it didn't make any difference.  It still only outputs tables.  I then thought "maybe it's the user rights only able to see tables ", so I logged in with the user and I can see and view stored procedures and functions, etc as well.

Am I missing something or is this perhaps a bug?

Thank you for your time.

**Comment by justinlettau** [comment]
Is there any output in the console when running `ssc pull`? Also, could you provide what your `ssc.json` file looks like?

**Comment by ryanhinton** [comment]
Hi Justin,

Thank you for getting back to me.  I did not get a chance to cancel this
issue after I did some more digging by combing through your code.  I
extracted the sql statement for objects and ran it in ssms for the user
account I am using for this and the result was consistent with no data.  So
I created a select statement to figure out which sys table in the statement
was prohibiting a result and it was the syscomments table.  Apparently, the
user does not have access to the text column but is able to make a select
statement using the table, so this user does have restrictions and there is
nothing wrong with your code.

Just an FYI while researching about how to gain access to syscomments.text, I read from
a Microsoft website that syscomments will become deprecated in future
releases.  There is a recommendation to use sys.sql_modules for any new
development.  Maybe you wrote it for backwards compatibility for sql2000,
but I just wanted to let you know my findings.

On another note, is there a way for us to be able to update these scripts (or something you recommend that we use alongside of sql-source-control)
back into the databases within the SDLC such as when having to update a QA
DB from a Dev DB, a Staging DB from a QA DB and then the Production DB from
a Staging DB?

Thanks again for your great work on this!

Regards,
Ryan

**Comment by justinlettau** [comment]
Thanks for the update and heads up about `syscomments`!

I would love to add some features like "pushing" changes to a database, comparing databases, generating diff scripts between databases, ect. It's just a matter of getting the time to work on it 😄

**Comment by ryanhinton** [comment]
I hear you.  Are you using anything in the interim to help you push the changes?

By the way, regarding `syscomments` deprecation, here is what I used while testing my DB to obtain the objects.  Instead of it being syscomments.text, the comparison is sys.sql_modules.definition in the following query.
```
SELECT sm.object_id, OBJECT_NAME(sm.object_id) AS object_name, o.type, o.type_desc, sm.definition  
FROM sys.sql_modules AS sm  
JOIN sys.objects AS o ON sm.object_id = o.object_id  
ORDER BY o.type; 
```

**Comment by justinlettau** [comment]
Not really. What we do currently is more of a manual process.

**Comment by ryanhinton** [comment]
Got you.  Well, I'm going to look into finding a way to make a `push` feature.  This style of JS coding is new to me but I am willing to learn it to figure out how to make a `push` feature for the CLI.  I have the same time restraints but this looks like it would be a fun experience to tackle.  If/when I do get something working, I have no problem passing it to you and you can do with it what you wish.  :-)

Thanks again, Justin!

**Comment by justinlettau** [comment]
Thanks! I have also added it to the project plan (https://github.com/justinlettau/sql-source-control/projects/1).
