### ISSUE TITLE
ssc pull creates truncate tables even tho they have foreign keys

### ISSUE THREAD

**Issue by Jaxelr** [justinlettau/sql-source-control#47]
## Type
What kind of issue is this?

- [x] Bug report.
- [ ] Feature request.

## Current Behavior
Given the following query:

```sql
CREATE TABLE [dbo].[Parent](
	[ParentId] [int] IDENTITY(1,1) NOT NULL,
	[ParentName] [varchar](24) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ParentId] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Child](
	[ChildId] [int] IDENTITY(1,1) NOT NULL,
	[ParentId] [int] NOT NULL,
	[ChildName] [varchar](24) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ChildId] ASC
)
) ON [PRIMARY]
GO

INSERT INTO	dbo.Parent(ParentName) SELECT 'Jaxel'
```

When i run an ssc pull combined with the data configuration for the parent table above, the command returns an invalid truncate table that will error with the message (`Cannot truncate table 'dbo.Parent' because it is being referenced by a FOREIGN KEY constraint.`). Current resulting data query

```sql
truncate table dbo.Parent
insert into dbo.Parent (ParentId, ParentName) values (1, 'Jaxel')
```

## Expected behavior

I expect the data query should replace the truncate with a delete from.
Like so:

```sql
DELETE FROM dbo.Parent
insert into dbo.Parent (ParentId, ParentName) values (1, 'Jaxel')
```

## Steps to Reproduce
Execute the following command on SQL Server:
```sql
CREATE TABLE [dbo].[Parent](
	[ParentId] [int] IDENTITY(1,1) NOT NULL,
	[ParentName] [varchar](24) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ParentId] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Child](
	[ChildId] [int] IDENTITY(1,1) NOT NULL,
	[ParentId] [int] NOT NULL,
	[ChildName] [varchar](24) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ChildId] ASC
)
) ON [PRIMARY]
GO

INSERT INTO	dbo.Parent(ParentName) SELECT 'Jaxel'
```
Add the data clause to the ssc.json file:

```json
{
  "connections": [
    {
      "name": "local",
      "server": "localhost",
      "database": "master",
      "port": 1433,
      "user": "sa",
      "password": ""
    }
  ],
  "data" : ["dbo.Parent"]
}
```

## Other Information

DB: SQL Server 2017
Platform: Win 10

**Comment by justinlettau** [comment]
v2.0.0 includes an `idempotency` option for data files! The default is still `truncate`, but you can configure to use delete from syntax.

https://github.com/justinlettau/sql-source-control#configuration

**Comment by Jaxelr** [comment]
Thanks a lot! 👍 👍
