### ISSUE TITLE
Primary keys w/multiple columns generate invalid SQL

### ISSUE THREAD

**Issue by winzig** [justinlettau/sql-source-control#48]
## Type
What kind of issue is this?

- [x] Bug report.
- [ ] Feature request.

## Current Behavior

If you create a table that has a primary key defined with multiple fields, you end up with a table definition like this from ssc:

```
create table [dbo].[MyTable]
(
    [KeyColumnA] int not null,
    [KeyColumnB] varchar(50) collate SQL_Latin1_General_CP1_CI_AS not null,
    constraint [PK_MyTable_KeyColumnA_KeyColumnB] primary key ([KeyColumnA] asc)
    constraint [PK_MyTable_KeyColumnA_KeyColumnB] primary key ([KeyColumnB] asc)
)
```
## Expected behavior

When I view how SQL Server defines the table definition, it looks more like this:

```
CREATE TABLE [dbo].[MyTable](
	[KeyColumnA] [int] NOT NULL,
	[KeyColumnB] [varchar](50) NOT NULL,
CONSTRAINT [PK_MyTable_KeyColumnA_KeyColumnB] PRIMARY KEY CLUSTERED 
(
	[KeyColumnA] ASC,
	[KeyColumnB] ASC
))
```

Actually, SQL Server does have some additional properties that it appends to the constraint (i.e. `WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]`) and to the table definition (i.e. `ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]`), and it would be great if ssc would support those as well, but getting it to generate valid SQL should be the priority I think.

## Steps to Reproduce

Run the SQL in the "Expected behavior" section, and then run `ssc pull` to see how it generates the SQL in the "Current behavior."

## Other Information

```
Microsoft SQL Server 2017 (RTM-CU3-GDR) (KB4052987) - 14.0.3015.40 (X64) 
	Dec 22 2017 16:13:22 
	Copyright (C) 2017 Microsoft Corporation
	Web Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

**Comment by ice1e0** [comment]
same problem occurs with indexes

**Comment by justinlettau** [comment]
Just landed a fix for the primary keys 🎉 Going to leave this issue open to fix the indexes too.
