### ISSUE TITLE
ssc pull data with empty values instead of null

### ISSUE THREAD

**Issue by Jaxelr** [justinlettau/sql-source-control#49]
## Type
What kind of issue is this?

- [x] Bug report.
- [ ] Feature request.

## Current Behavior

Given the following sql script:
```sql
USE master
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[foo](
	[field] [varchar](10) NOT NULL,
	[field2] [varchar](2) NOT NULL,
	[field3] [char](1) NULL
) ON [PRIMARY]
GO

INSERT INTO	dbo.foo(field, field2)
SELECT 'bar', 'b'
```
Using the following ssc.json configuration:
```json
{
  "connections": [
    {
      "name": "dev",
      "server": "localhost",
      "database": "master",
      "port": 1433,
      "user": "",
      "password": ""
    }
  ],
  "data" : ["dbo.foo"]
}
```
ssc pulls generates the following insert script, when configuring the table as pull data:

```sql
TRUNCATE TABLE dbo.foo

SET IDENTITY_INSERT dbo.foo ON

INSERT INTO dbo.foo (field, field2, field3) VALUES ('bar', 'b', )

SET IDENTITY_INSERT dbo.foo OFF
```

The resulting script being invalid SQL, since NULL values from tables are generated with an empty value when creating the insert.

## Expected behavior

The insert value should include the NULL clause for NULL values.

```sql
TRUNCATE TABLE dbo.foo

SET IDENTITY_INSERT dbo.foo ON

INSERT INTO dbo.foo (field, field2, field3) VALUES ('bar', 'b', NULL)

SET IDENTITY_INSERT dbo.foo OFF
```

## Steps to Reproduce

1. Execute the script above.
2. use the ssc.json configuration included above (adding user and pass per environment).
3. execute ssc pull

## Other Information

DB: SQL Server 2017
Platform: Win 10

**Comment by justinlettau** [comment]
Fixed in v2.0.2. Thanks for PR @Jaxelr 👍
