### ISSUE TITLE
Order of indexes on tables is not fixed

### ISSUE THREAD

**Issue by lmeyer1** [justinlettau/sql-source-control#59]
## Description
When pulling the same database again, the order of the indexes in the files `tables/dbo.*.sql` may change. As a consequence, these files show up as modified in git. This hampers the main reason of being of this tool: allow to pull a database into git.

The same thing can happen with table constraints.

## Expected behavior
Any file created by this tool should change only if the structure of the database object itself changed.

## Steps to Reproduce
This is difficult to reproduce, since it is happening only occasionally. It happened on my third pull on about 1% of all tables in 3 out of 16 databases.

## Other Information
It could be helpful to order the indexes in alphabetical order.

**Comment by lmeyer1** [comment]
Hello Justin,

I looked at your source code, and your are ordering by schema_id.
I exported the same files from the production database and from a copy of the database (backup and restore). I speculate: maybe the schema_id of the same index changed while restoring the database on another server ? So I'm no longer sure this is really a bug.

**Comment by justinlettau** [comment]
I've never seen this issue, so your assumption is probably right. Feel free to re-open this issue if you find something else. Thanks.
