### ISSUE TITLE
If the files already exist, they are not updated, but deleted

### ISSUE THREAD

**Issue by lmeyer1** [justinlettau/sql-source-control#60]
## Describe the Issue
Using the command line `cmd` on Windows 10, `ssc pull` will not update the files, but delete them if they already exist.

    C:\..\git\database_folder>ssc pull
    √ Successfully added 1098, updated 0, and removed 1098 files.

## Expected behavior
As advertised, the tool should update changed files, based on `cache.json`

## Steps to Reproduce
Run `ssc pull` in Windows terminal two times one after another.

## Workaround
Delete all files before `ssc pull`

    rmdir /s /q database_folder/
    md database_folder/
    copy ssc.json database_folder/ssc.json
    cd database_folder/
    ssc pull

**Comment by justinlettau** [comment]
@lmeyer1 I can't reproduce this issue. I'm also on Windows 10. Can you provide some details on your config, database, etc?

**Comment by lmeyer1** [comment]
Hello,
I looked into your code and found the issue:

My config file had `root: '.'`. 

In `file-utility.ts:174`, `existingFiles` was something like `[ './schemas/dbo.sql', ... ]`, but in `file-utility.ts:148` after normalizing, the filename was `'schemas/dbo.sql`.

After changing the configuration to `root: './'`, normalization works as expected, and files are no longer removed.

**Comment by justinlettau** [comment]
I'm glad you got this resolved. I'll see about adding some handling for that specific config scenario to avoid this issue in the future.
