### ISSUE TITLE
RequestError: The SELECT permission was denied on the object 'sysjobsteps', database 'msdb', schema 'dbo'.

### ISSUE THREAD

**Issue by winzig** [justinlettau/sql-source-control#65]
## Describe the Issue

I updated from 1.9.1 to 2.0.2 and then ran `ssc pull`, and ssc seems to get stuck after this error appears:

```
✖ RequestError: The SELECT permission was denied on the object 'sysjobsteps', database 'msdb', schema 'dbo'.
```

I reviewed the CHANGELOG and can see that SQL job info is now being stored by SSC. However, I'm using SQL Server on AWS RDS, and I suspect this is why my user doesn't have permission to access the jobs (AWS RDS handles backups and other things typically done in jobs). 

I tried to figure out how to skip jobs during the processing, but failed. I thought maybe this would work in my json config file, but it didn't:

```json
{
  "output": {
    "jobs": false
  }
}
```

Any recommendations?

**Comment by justinlettau** [comment]
@winzig Good catch! Sorry about that 😊 I just release v2.1.1 which should fix this so the following config will work:

```
{
  "output": {
    "jobs": false
  }
}
```

Let me know if you have further issues. Thanks.

**Comment by winzig** [comment]
Perfect, works for me now.
