### ISSUE TITLE
✖ RequestError: Reference to database and/or server name in 'msdb.dbo.sysjobs' is not supported in this version of SQL Server.

### ISSUE THREAD

**Issue by DanielOverdevest** [justinlettau/sql-source-control#66]
## Describe the Issue

With the new version 2.1.1 it is not working anymore with Azure SQL database (basic tier)

**Comment by justinlettau** [comment]
Duplicate of #65 . If you don't have access to jobs, you need to set output to `false` for jobs.
See https://github.com/justinlettau/sql-source-control/issues/65#issuecomment-456629033 for details.

**Comment by DanielOverdevest** [comment]
This works well! Thanks for the hint. Maybe you can specify the error message that you can skip the jobs.
