### ISSUE TITLE
Getting tedious deprecated message when using ssc push

### ISSUE THREAD

**Issue by ryanhinton** [justinlettau/sql-source-control#68]
## Describe the Issue
When executing `ssc push`, I received tedious deprecated Passing non-number values for options.port will throw an error in future tedious versions.  Please pass a number instead. ..\..\..\android\npm\node_modules\sql-source-control\node_modules\mssql\lib\tedious.js:232:23

## Expected behavior
I should not be receiving a warning
Todo

## Steps to Reproduce
`ssc push`
type 'y' and Enter
Warning received.
n/a

## Other Information

n/a

**Comment by unybble** [comment]
All you have to do is change the port to a number:
NO (generates above error):
```
{
  "connections": [
    {
      "name": "dev",
      "server": "123.45.67.89",
      "port": "3307",
      "database": "MyDB",
      "user": "user",
      "password": "userpw"
    }
  ]
}
```

YES  (no error):
```
{
  "connections": [
    {
      "name": "dev",
      "server": "123.45.67.89",
      "port": 3307,
      "database": "MyDB",
      "user": "user",
      "password": "userpw"
    }
  ]
}
```
I think a more descriptive bug is that when initiating a connection with "_ssc init_", the wizard generates port as a string. The fix request should be for the wizard from _ssc init_ to insert as a number and not a string.

As long as **you** have put a number, you won't get this error. Hope it helps.

**Comment by unybble** [comment]
Actually looks like this was fixed: https://github.com/justinlettau/sql-source-control/issues/116

I should sync with master! :)

**Comment by lmeyer1** [comment]
This is fixed in the `master` branch. You can close this issue.
