### ISSUE TITLE
ssc pulldata

### ISSUE THREAD

**Issue by sbechet** [justinlettau/sql-source-control#8]
Add ssc pulldata to save data in .sql format

**Comment by winzig** [comment]
This would be awesome to have for lookup tables. Perhaps some way to designate which of your tables you want to track in this way.

**Comment by winzig** [comment]
@justinlettau I'm trying to figure out how to use this new feature. It looks like we need to define a `data` array of globs in the config .json file, which I've done:

`"data": ["dbo.Coupons", "dbo.DiscussionTopics", "dbo.Lookup*", "dbo.Partners", "dbo.Webheads"]`

I'm running `ssc pull` on the command line, but I'm not seeing anything new generated. Am I missing anything? Thanks!

**Comment by justinlettau** [comment]
@winzig Yeah, the `data` glob is correct. Are you running v1.8.0?

**Comment by winzig** [comment]
Yep

**Comment by justinlettau** [comment]
Well, it should be generating files in the `_sql-database/data/` directory. Can you post your config?

**Comment by winzig** [comment]
The only other thing defined in my config is my SQL connection properties. So it's just that, and the `data` glob array. Do I need something else defined in there to tell it to do the data pull?

**Comment by winzig** [comment]
hmmm... I think I see the issue. It looks like I have both a global and a local installation of ssc. The local one appears to be 1.7.1. Sorry!

**Comment by justinlettau** [comment]
Glad you figured it out!

**Comment by winzig** [comment]
It's mostly working for me now, but data entry for `"dbo.Lookup*"` seems to cause it to choke. I'm guessing this type of file glob is not allowed?

**Comment by justinlettau** [comment]
Hmm, I guess I the docs are wrong (sorry). I think currently is is a list of table names, not a glob.
