### ISSUE TITLE
Default constraints should be scripted with their name

### ISSUE THREAD

**Issue by lmeyer1** [justinlettau/sql-source-control#80]
The table scripts do not contain the name of default constraints. This is not a bug in itself, but it can lead to unexpected behavior, if one uses the `create table` scripts to create the same table in two different databases.

## Expected behavior
I'd expect, that two tables created with the same script should be identical. As for now, each table differs in regards to the names of the default constraints, because SQL Server auto-generates random names for the constraints that are not explicitly name at creation time.

## Steps to Reproduce
Use a `create table` statement in two different databases to create a copy of the same table. The default constraints will have different random names.

## Other Information
I modified the code in order to include the default constraint name in the create table statement (`[active] tinyint NOT NULL CONSTRAINT [df_fields_active] DEFAULT(0),` instead of `[active] tinyint NOT NULL DEFAULT(0),`)
I plan to create a pull request with these changes.

**Comment by justinlettau** [comment]
@lmeyer1 Decided to add this as a configuration setting just in case for others. 

You can opt into this via `"includeConstraintName": true` in your config fie. You can see it here (0235d948e87b26a2fe592df24c99a98cbd285948).
